config/routes.rb
Rails.application.routes.draw do
  resource :s_session

  resources :users

  root 'students#index'

  resources :students do
    resources :sessions
  end
end

app/models/session.rb
# get rid of rubocop error
class Session < ActiveRecord::Base
  belongs_to :student

  validates :date, presence: true
  validates :minutes, presence: true, numericality: {
    only_integer: true,
    greater_than: 0
  }
  validates :notes, presence: true, length: { minimum: 4 }
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :sessions, dependent: :destroy

  validates :first_name, :last_name, :grade, :min_hours, presence: true

  def fullname
    @fullname = "#{first_name} #{last_name}"
  end

  def self.first_name_asc
    order('first_name asc')
  end

  def years_old(age)
    now = Time.now.utc.to_date
    now.year - age.year - ((now.month > age.month || (now.month == age.month && now.day >= age.day)) ? 0 : 1)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true,
                    format: /\A\S+@\S+\z/,
                    uniqueness: { case_sensitive: false }

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def require_signin
    unless current_user
      redirect_to new_s_session_url, alert: 'Please sign in first!'
    end
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user  
end

app/controllers/s_sessions_controller.rb
class SSessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.name}!"
      redirect_to user
    else
      flash.now[:alert] = 'Invalid email/password combination!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Successfully signed out'
  end
end

app/controllers/sessions_controller.rb
# get rid of rubocop error
class SessionsController < ApplicationController
  before_action :set_student

  def index
    @session = @student.sessions
  end

  def new
    @session = @student.sessions.new
  end

  def create
    @session = @student.sessions.new(session_params)
    if @session.save
      flash[:notice] = 'Therapy note successfully added'
      redirect_to student_sessions_path(@student)
    else
      render :new
    end
  end

  def show
    @session = @student.sessions.find(params[:id])
  end

  def edit
    @session = @student.sessions.find(params[:id])
  end

  def update
    @session = @student.sessions.find(params[:id])
    if @session.update(session_params)
      flash
      redirect_to student_sessions_path(@student), notice: 'Note successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @session = @student.sessions.find(params[:id])
    @session.destroy
    redirect_to student_sessions_url
  end

  private

  def set_student
    @student = Student.find(params[:student_id])
  end

  def session_params
    params.require(:session).permit(
      :date,
      :minutes,
      :therapy,
      :notes
    )
  end
end

app/controllers/students_controller.rb
# get rid of rubocop error
class StudentsController < ApplicationController
  def index
    @students = Student.first_name_asc
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      flash
      redirect_to @student, notice: 'Student successfully updated!'
    else
      render :edit
    end
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash
      redirect_to @student, notice: 'Student successfully added.'
    else
      flash
      render :new
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_url
  end

  private

  def student_params
    params.require(:student).permit(
      :first_name,
      :last_name,
      :age,
      :grade,
      :triennial,
      :iep_date,
      :min_hours,
      :diagnosis,
      :dismissed
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Sign up successful'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Update successful'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_url, alert: 'Account deleted'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, class: class_name) do
      link_to link_text, link_path
    end
  end
end

app/helpers/s_sessions_helper.rb
module SSessionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper

  def show_checkmark
    if @student.triennial == true
      content_tag(:i, '', class: 'fi-check')
    else
      content_tag(:i, '', class: 'fi-prohibited')
    end
  end

  def dismissed_checkmark
    if @student.dismissed == true
      content_tag(:i, '', class: 'fi-check')
    else
      content_tag(:i, '')
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
/ Navbar
%link{:href => "http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css", :rel => "stylesheet"}
  %nav.menu
    %h1.name
      %i.fi-clipboard-notes
      CASELOAD
    %ul.inline-list
      %li
        = nav_link 'All Students', root_path
      %li
        = nav_link 'Add Student', new_student_path
    %ul.inline-list.hide-for-small-only.account-action
      - if current_user
        = nav_link current_user.name, current_user
        = nav_link 'Account Settings', edit_user_path(current_user)
        = link_to 'Sign Out', s_session_path, method: :delete
      - else
        %li
          %a{"data-reveal-id" => "myModal", :href => "#"} Login
    %a.account.hide-for-medium-up{"data-reveal-id" => "myModal", :href => "#"}
      %i.fi-unlock
  / modal content
  #myModal.reveal-modal{"aria-hidden" => "true", "aria-labelledby" => "login or sign up", "data-reveal" => "", :role => "dialog"}
    .row
      .large-6.columns.auth-plain
        .signup-panel.left-solid
          %p.welcome Registered Users
          = form_tag(s_session_path) do
            .row.collapse
              .small-2.columns
                %span.prefix
                  %i.fi-torso-female
              .small-10.columns
                = text_field_tag :email, nil
            .row.collapse
              .small-2.columns
                %span.prefix
                  %i.fi-lock
              .small-10.columns
                = password_field_tag :password, nil
            = submit_tag 'Login', class: 'button'
      .large-6.columns.auth-plain
        .signup-panel.newusers
          %p.welcome New User?
          %p Please use this option to create a new account. As a registered user, you will have access to the students on your caseload.
          %br
            %a.button{:href => new_user_path} Sign Up
    %a.close-reveal-modal{"aria-label" => "Close"} ×

/ Sidebar

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Caseload" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role='main'>
      <%= render 'layouts/messages' %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/s_sessions/create.html.erb
<h1>Welcome User</h1>

app/views/s_sessions/new.html.erb
<h1>Sign In</h1>

app/views/shared/_errors.html.erb
 <% if object.errors.any? %>
 <section id="errors">
   <header data-alert class='alert-box alert round'>
     <p>
       <%= object.class.name.titleize.downcase %> could not be saved.
     </p>
    </header>
   <ul>
     <% object.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
   </ul>
 </section>
 <% end %>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <%= render 'shared/errors', object: @student %>
  <div class='row'>
    <div class='large-6 columns'>
      <div class='large-6 columns'>
        <%= f.label :first_name %>
        <%= f.text_field :first_name, autofocus: true, tabindex: '1' %>

        <%= f.label :age, 'Date of birth' %>
        <%= f.date_field :age, tabindex: '3' %>
      </div>
      <div class='large-6 columns'>
        <%= f.label :last_name %>
        <%= f.text_field :last_name, tabindex: '2' %>

        <%= f.label :grade %>
        <%= f.number_field :grade, tabindex: '4' %>
      </div>
      <div class='large-12 columns'>
        <%= f.label :diagnosis %>
        <%= f.text_area :diagnosis, tabindex: '5' %>
      </div>
    </div>
    <div class='large-6 columns'>
      <div class='large-6 columns'>
        <%= f.label :iep_date %>
        <%= f.date_field :iep_date, tabindex: '6' %>

        <%= f.check_box :triennial, tabindex: '8' %>
        <%= label_tag(:triennial, 'Triennial due this year?') %>
      </div>
      <div class='large-6 columns'>
        <%= label_tag(:min_hours, 'IEP Minutes') %>
        <%= f.number_field :min_hours, tabindex: '7' %>

        <%= f.check_box :dismissed, tabindex: '9' %>
        <%= label_tag(:dismissed, 'Dismissed?') %>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='large-6 columns'>
      <div class='large-6 columns'>
          <%= f.submit class: 'button small round' %>
          <%= link_to 'Cancel', students_path, method: 'get', class: 'button secondary round small' %>
      </div>
    </div>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Edit <%= @student.first_name %> <%= @student.last_name%></h1>

<%= render 'form' %>

<div class='row'>
  <div class='large-6 columns'>
    <div class='large-6 columns'>
      <%= link_to 'Delete Student', student_path(@student), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button alert small round' %>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<h1>All Students</h1>
<div class='row'>
  <div class='large-12 columns'>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Grade</th>
          <th>Diagnosis</th>
          <th>IEP Date</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @students.each do |student| %>
        <tr>
          <td><%= student.fullname %></td>
          <td><%= student.grade %></td>
          <td><%= student.diagnosis %></td>
          <td><%= l student.iep_date, format: :short_date %></td>
          <td>
            <ul class='button-group round caseload-index'>
              <li class='annoyed'><%= link_to 'Show Student', student, class: 'button tiny' %></li>
              <li><%= link_to 'Write Note', new_student_session_path(student), class: 'button tiny' %></li>
              <li><%= link_to 'Show Therapy Notes', student_sessions_path(student), class: 'button tiny' %></li>
            </ul>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/students/new.html.erb
<h1>Add New Student</h1>

<%= render 'form' %>

app/views/students/show.html.erb
<article>
      <div class='student-header-wrapper'>
  <header class='row'>

      <div class='large-12 columns'>
        <div class='large-8 columns'>
          <h1><%= @student.first_name %> <%= @student.last_name %></h1>
        </div>
        <div class='large-2 columns'>
          <h5>Triennial?</h5>
          <%= show_checkmark %>
        </div>
        <div class='large-2 columns'>
          <h5>Dismissed?</h5>
          <%= dismissed_checkmark %>
        </div>
      </div>
    </div>
  </header>

  <div class='row demographics'>
    <div class='large-12 columns'>
      <div class='large-3 columns'>
        <h4>Age</h4>
        <%= @student.years_old(@student.age) %>
      </div>
      <div class='large-3 columns'>
        <h4>Grade</h4>
        <%= @student.grade %>
      </div>
      <div class='large-3 columns'>
        <h4>IEP Date</h4>
        <%= l @student.iep_date, format: :short_date %>
      </div>
      <div class='large-3 columns'>
        <h4>IEP Minutes</h4>
        <%= @student.min_hours %>
      </div>
    </div>
  </div>
  <div class='diagnosis'>
    <div class='row'>
      <div class='large-12 columns'>
        <h4>Diagnosis</h4>
        <%= @student.diagnosis %>
      </div>
    </div>
  </div>
</article>

<div class='show_student_buttons'>
  <div class='row'>
    <ul class='button-group round'>
      <li><%= link_to 'Write Note', new_student_session_path(@student), class: 'button small' %></li>
      <li><%= link_to 'Show Therapy Notes', student_sessions_path(@student), class: 'button small' %></li>
    </ul>
    <ul class='button-group round'>
      <li><%= link_to 'Edit', edit_student_path(@student), class: 'button small' %></li>
    </ul>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/errors', object: @user %>
  <fieldset>
    <ul>
      <li class='required'>
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class='required'>
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </li>
      <li class='required'>
        <%= f.label :password %>
        <%= f.password_field :password, size: 40 %>
      </li>
      <li class='required'>
        <%= f.label :password_confirmation, 'Confirm Password' %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </li>
    </ul>
    <p>
      <% if @user.new_record? %>
        <%= f.submit 'Create Account', class: 'button small round' %>
      <% else %>
        <%= f.submit 'Update Account', class: 'button small round' %>
      <% end %>
    </p>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<header id='content-header'>
  <h1>Edit</h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<header id='content-header'>
  <h1><%= pluralize(@users.size, 'User') %></h1>
</header>

<ul id='users'>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<header id='content-header'>
  <h1>Sign Up</h1>
</header>

<%= render 'form' %>

app/views/users/show.html.erb
<article id='user'>
  <header>
    <h1><%= @user.name %></h1>
    <h2><%= @user.email %></h2>
  </header>
  <footer>
    <nav>
      <%= link_to 'Edit', edit_user_path(@user), class: 'button small' %>
      <%= link_to 'Delete Account', @user,  method: :delete,
                                            data: { confirm: 'Are you sure?' },
                                            class: 'button small alert' %>
    </nav>
  </footer>
</article>